SQUIRREL_STORE_CONFIG_PATH = "SQUIRREL_STORE_CONFIG_PATH"
SQUIRREL_SCHEMA_CONFIG_PATH = "SQUIRREL_SCHEMA_CONFIG_PATH"
SQUIRREL_DEFAULT_REPO = "SQUIRREL_DEFAULT_REPO"
SQUIRREL_DEFAULT_GATHER_LOC = "SQUIRREL_DEFAULT_GATHER_LOC"